services:
  mongo:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-flash}
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/mental_health_db}
      - SECRET_KEY=${SECRET_KEY:-change-me}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo_data:
