apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.commonLabels" . | nindent 4 }}
data:
  GEMINI_MODEL: {{ .Values.env.GEMINI_MODEL | quote }}
