apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | quote }}
  MONGO_URI: {{ .Values.secret.MONGO_URI | quote }}
  GEMINI_API_KEY: {{ .Values.secret.GEMINI_API_KEY | quote }}
  GOOGLE_API_KEY: {{ .Values.secret.GOOGLE_API_KEY | quote }}
  WTF_CSRF_SECRET_KEY: {{ .Values.secret.WTF_CSRF_SECRET_KEY | quote }}
  PORT: {{ .Values.secret.PORT | quote }}
  FLASK_DEBUG: {{ .Values.secret.FLASK_DEBUG | quote }}
