apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: mental-health
  labels:
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/part-of: mental-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-app
    spec:
      containers:
        - name: flask-app
          image: ofirjean/mental-health-assistant:latest  # change tag if you have one
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: app-secrets
            - configMapRef:
                name: app-config
          ports:
            - name: http
              containerPort: 5000
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 15
            periodSeconds: 10
