apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: mental-health
  labels:
    app.kubernetes.io/name: flask-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: flask-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30080
