apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mental-health
  labels:
    app.kubernetes.io/name: mongo
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    app.kubernetes.io/name: mongo
