apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: mental-health
type: Opaque
stringData:
  SECRET_KEY: "dev-secret-change-me"
  MONGO_URI: "mongodb://mongo:27017/mental_health_db"
  GEMINI_API_KEY: ""
  GOOGLE_API_KEY: ""
  WTF_CSRF_SECRET_KEY: ""
  PORT: "5000"
  FLASK_DEBUG: "0"
