USER-SUPPLIED VALUES:
controller:
  javaOpts: -Djenkins.install.runSetupWizard=false
  nodePort: 32010
  persistence:
    enabled: true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
  servicePort: 8080
  serviceType: NodePort
  targetPort: 8080
