image:
  repository: ofirjean/mental-health-assistant
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000

env:
  GEMINI_MODEL: "gemini-1.5-flash"

secret:
  SECRET_KEY: "0dda2fec75c2b1a4ebf1795c96f9ff405a149f2e87932b26e99327f521037dd6"
  MONGO_URI: "mongodb://mongo:27017/mental_health_db"
  GEMINI_API_KEY: ""
  GOOGLE_API_KEY: ""
  WTF_CSRF_SECRET_KEY: ""
  PORT: "5000"
  FLASK_DEBUG: "0"

mongo:
  image: "mongo:8.0"
  servicePort: 27017
  storage: "2Gi"

sanityTest:
  enabled: true
  image: curlimages/curl:8.10.0

prometheus:
  enabled: false
