apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  serviceAccountName: jenkins

  volumes:
    - name: workspace
      emptyDir: {}
    - name: docker-graph
      emptyDir: {}

  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest-jdk17
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent

    - name: builder
      image: python:3.11-alpine
      # Use a more explicit approach that handles the login shell issue
      command: 
        - /bin/sh
        - -c
        - |
          echo "Installing packages..."
          apk update
          apk add --no-cache git docker-cli bash coreutils curl
          echo "Verifying installation..."
          git --version
          docker --version || echo "Docker client installed"
          echo "✅ Container ready!"
          # Ensure PATH is correct for login shells
          echo 'export PATH="/usr/local/bin:/usr/bin:/bin:$PATH"' >> /etc/profile
          exec sleep infinity
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        # Ensure PATH is set correctly
        - name: PATH
          value: "/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent

    - name: dind
      image: docker:27-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      args:
        - --host=tcp://0.0.0.0:2375
        - --storage-driver=overlay2
      volumeMounts:
        - name: docker-graph
          mountPath: /var/lib/docker
        - name: workspace
          mountPath: /home/jenkins/agent