# ci/jenkins/build-agents.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  serviceAccountName: jenkins
  volumes:
    - name: workspace
      emptyDir: {}
    - name: docker-graph
      emptyDir: {}
  containers:
    - name: jnlp
      image: ghcr.io/jenkinsci/inbound-agent:latest-jdk17
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent
    - name: builder
      image: alpine:3.20
      # Install tools once, then keep the container alive
      command: ['sh','-c','apk add --no-cache git docker-cli bash coreutils python3 py3-pip >/dev/null && sleep infinity']
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent
    - name: dind
      image: docker:27-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      args:
        - --host=tcp://0.0.0.0:2375
        - --storage-driver=overlay2
      volumeMounts:
        - name: docker-graph
          mountPath: /var/lib/docker
