apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-recover-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    # host absolute path (WITHOUT the /host prefix)
    path: /var/lib/docker/volumes/ci_jenkins_home/_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 8Gi
  volumeName: jenkins-recover-pv
